twig:
    paths: ['%kernel.project_dir%/templates', '%kernel.project_dir%/var/dynamic-templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # form_themes:
    #     - 'form/fields.html.twig'
